const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
process.env.DATA_FILE = path.resolve('work/test-platform.json'); process.env.TOKEN_SECRET = 'test-secret'; process.env.PORT = '4010';
fs.rmSync(process.env.DATA_FILE, { force: true });
const { server } = require('../src/server');
const base = 'http://127.0.0.1:4010';
let alphaToken; let betaToken;
async function request(pathname, options = {}) { const response = await fetch(base + pathname, options); return { response, body: response.status === 204 ? null : await response.json() }; }
test.before(async () => { await new Promise((resolve) => server.listen(4010, resolve)); const alpha = await request('/auth/login', { method: 'POST', body: JSON.stringify({ email: 'owner@alpha.test', password: 'demo-password' }) }); const beta = await request('/auth/login', { method: 'POST', body: JSON.stringify({ email: 'owner@beta.test', password: 'demo-password' }) }); alphaToken = alpha.body.token; betaToken = beta.body.token; });
test.after(() => { server.close(); fs.rmSync(process.env.DATA_FILE, { force: true }); });
test('public config and versioned bundle are cacheable', async () => { const config = await request('/public/widgets/widget_welcome/config'); assert.equal(config.response.status, 200); assert.match(config.response.headers.get('cache-control'), /max-age=300/); const bundle = await fetch(base + '/widget.v1.js'); assert.match(bundle.headers.get('cache-control'), /immutable/); });
test('CORS preflight and malformed submissions return clean errors', async () => { const preflight = await fetch(base + '/public/submissions', { method: 'OPTIONS', headers: { Origin: 'http://localhost:5500' } }); assert.equal(preflight.status, 204); assert.equal(preflight.headers.get('access-control-allow-origin'), '*'); const bad = await request('/public/submissions', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ widgetId: 'widget_welcome', data: { email: 'not-an-email' } }) }); assert.equal(bad.response.status, 422); assert.equal(bad.body.error, 'validation failed'); });
test('submission is idempotent, enriched through fallback, and survives failed side effect', async () => { process.env.GEO_PROVIDER_A_MODE = 'down'; process.env.GEO_PROVIDER_B_MODE = 'ok'; const options = { method: 'POST', headers: { 'content-type': 'application/json', 'idempotency-key': 'proof-idempotency', 'x-force-side-effect-fail': 'true' }, body: JSON.stringify({ widgetId: 'widget_welcome', data: { email: 'visitor@example.test', name: 'Visitor' } }) }; const first = await request('/public/submissions', options); const retry = await request('/public/submissions', options); assert.equal(first.response.status, 201); assert.equal(retry.response.status, 200); assert.equal(retry.body.idempotentReplay, true); const dash = await request('/admin/submissions', { headers: { authorization: `Bearer ${alphaToken}` } }); assert.equal(dash.body.items.length, 1); assert.equal(dash.body.items[0].geo.provider, 'mock-ipapi'); });
test('honeypot blocks spam and per-IP/widget rate limiting returns 429', async () => { const spam = await request('/public/submissions', { method: 'POST', headers: { 'content-type': 'application/json', 'x-forwarded-for': '198.51.100.10' }, body: JSON.stringify({ widgetId: 'widget_welcome', honeypot: 'bot', data: { email: 'bot@example.test' } }) }); assert.equal(spam.response.status, 422); const payload = JSON.stringify({ widgetId: 'widget_welcome', data: { email: 'burst@example.test' } }); let last; for (let i = 0; i < 9; i++) last = await request('/public/submissions', { method: 'POST', headers: { 'content-type': 'application/json', 'x-forwarded-for': '198.51.100.11', 'idempotency-key': `burst-${i}` }, body: payload }); assert.equal(last.response.status, 429); });
test('tenant B cannot inspect tenant A widget or submissions', async () => { const widget = await request('/admin/widgets/widget_welcome', { headers: { authorization: `Bearer ${betaToken}` } }); assert.equal(widget.response.status, 404); const rows = await request('/admin/submissions', { headers: { authorization: `Bearer ${betaToken}` } }); assert.equal(rows.body.items.length, 0); });
