module.exports = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#ffffff">
  <title>Leadly — Convert attention into leads</title>
  <style>
    :root{--ink:#121836;--muted:#68718e;--line:#e8eaf4;--violet:#654be8;--mint:#19bfb8;--soft:#f4f2ff;--navy:#171a3d}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fdfdff;color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button{font:inherit}a{text-decoration:none;color:inherit}.wrap{width:min(1180px,calc(100% - 48px));margin:auto}
    .nav{height:82px;display:flex;align-items:center;justify-content:space-between;gap:28px}.brand{display:flex;align-items:center;gap:11px;font-weight:850;font-size:27px;letter-spacing:-1.7px}.logo{display:grid;place-items:center;width:43px;height:43px;border-radius:13px;background:linear-gradient(135deg,#8a73ff,#2bc9c2);color:#fff;font-size:23px}.links{display:flex;gap:36px;color:#5d6683;font-size:15px;font-weight:600}.links a:hover{color:var(--violet)}
    .button{border:0;border-radius:12px;padding:13px 19px;background:var(--violet);color:#fff;font-weight:750;cursor:pointer;box-shadow:0 10px 22px #654be839;transition:transform .18s,box-shadow .18s}.button:hover{transform:translateY(-2px);box-shadow:0 14px 27px #654be84b}.button.light{color:#5541c4;background:#efedff;box-shadow:none}.button.dark{background:var(--navy);box-shadow:none}
    .hero{padding:79px 0 92px;display:grid;grid-template-columns:minmax(0,1.02fr) minmax(440px,.98fr);gap:46px;align-items:center;overflow:hidden}.tag{display:inline-flex;align-items:center;gap:9px;border:1px solid #dcd6ff;background:#faf9ff;border-radius:999px;padding:8px 13px;color:#5544bc;font-size:13px;font-weight:800}.pulse{width:8px;height:8px;border-radius:50%;background:#31c7b5}.hero h1{font-size:clamp(43px,4.4vw,65px);line-height:1.04;letter-spacing:-3.2px;margin:20px 0}.gradient{background:linear-gradient(100deg,#765bff,#15c5bd);-webkit-background-clip:text;background-clip:text;color:transparent}.intro{max-width:555px;color:var(--muted);font-size:18px;line-height:1.65;margin:0}.hero-actions{display:flex;gap:13px;flex-wrap:wrap;margin-top:29px}.note{font-size:12px;color:#848ba2;margin:16px 0 0}
    .preview{position:relative;width:100%;max-width:520px;margin:0 auto;padding:34px 34px 46px}.aurora{position:absolute;inset:0;background:radial-gradient(circle at 72% 26%,#d3f9f5,transparent 37%),radial-gradient(circle at 16% 76%,#e5ddff,transparent 46%);filter:blur(12px)}.form-card{position:relative;background:#fff;border:1px solid #e6e6f0;border-radius:22px;padding:30px;box-shadow:0 26px 65px #29255321}.form-card h2{font-size:25px;letter-spacing:-1.1px;margin:0}.form-card p{font-size:14px;line-height:1.55;color:#747c96;margin:8px 0 20px}.field-label{display:block;margin:16px 0 7px;font-size:11px;font-weight:850;color:#545b77}.fake-input{height:45px;border:1px solid #dfe2ed;border-radius:9px;padding:12px;color:#a1a8bc;font-size:13px}.fake-submit{width:100%;margin-top:20px;padding:13px;border:0;border-radius:9px;background:var(--navy);color:#fff;font-weight:750}.chip{position:absolute;z-index:2;background:rgba(255,255,255,.96);border:1px solid #e7e5f1;border-radius:11px;padding:10px 12px;box-shadow:0 10px 23px #312b5c17;font-size:12px;font-weight:800;white-space:nowrap}.chip-top{right:0;top:0}.chip-bottom{left:0;bottom:0}.chip-dot{color:#1d1f4a;margin-right:5px}
    .trust{background:var(--navy);color:#fff}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;padding:25px 0}.stat b{display:block;font-size:22px}.stat span{font-size:12px;color:#bbc0d8}.section{padding:92px 0}.eyebrow{color:#5a48c6;font-size:12px;font-weight:850;letter-spacing:.1em}.section h2{font-size:clamp(31px,3.3vw,43px);letter-spacing:-2px;margin:11px 0}.section-copy{max-width:590px;color:var(--muted);font-size:16px;line-height:1.65}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:36px}.feature{padding:26px;background:#fff;border:1px solid var(--line);border-radius:16px}.feature-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:#eeebff;color:#604ada;font-size:19px}.feature h3{margin:18px 0 8px;font-size:17px}.feature p{color:var(--muted);font-size:14px;line-height:1.58;margin:0}
    .workspace{padding:84px 0;background:linear-gradient(135deg,#f4f1ff,#effcfb)}.panel{margin-top:33px;border:1px solid #e6e7f0;border-radius:18px;background:#fff;box-shadow:0 20px 55px #29255312;overflow:hidden}.panel-head{padding:17px 22px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.panel-head b{font-size:14px}.live-status{font-size:12px;color:#139484;background:#e8fbf6;border-radius:999px;padding:6px 10px}.dashboard{display:grid;grid-template-columns:175px 1fr;min-height:316px}.sidebar{padding:17px;background:#fbfbff;border-right:1px solid var(--line);font-size:13px;color:#737a94}.sidebar div{padding:10px;margin-bottom:4px;border-radius:8px}.sidebar .selected{background:#efedff;color:#5745c8;font-weight:800}.main-panel{padding:24px}.overview{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric{border:1px solid var(--line);border-radius:10px;padding:15px}.metric span{font-size:11px;color:#747b94}.metric b{display:block;font-size:24px;margin-top:5px}.lead-table{margin-top:20px;border:1px solid var(--line);border-radius:10px;overflow:hidden;font-size:12px}.lead-row{display:grid;grid-template-columns:1.3fr 1fr 1fr;padding:11px 14px;border-bottom:1px solid var(--line)}.lead-row:last-child{border-bottom:0}.lead-row.heading{background:#fbfbff;color:#737a94;font-weight:800}
    .live-demo{display:none;margin-top:35px;background:#fff;border:1px solid var(--line);border-radius:16px;padding:26px}.live-demo h3{margin:0}.live-demo p{color:var(--muted);font-size:14px;line-height:1.6}.login{display:none;margin-top:18px;padding-top:17px;border-top:1px solid var(--line)}.login input{width:190px;max-width:100%;margin:4px;padding:11px;border:1px solid #dfe2ed;border-radius:8px}.message{font-size:13px;color:#5d6680;margin-top:10px}.cta{margin-top:28px;padding:25px;background:var(--navy);border-radius:15px;color:#fff;display:flex;justify-content:space-between;align-items:center;gap:16px}.cta p{margin:6px 0 0;color:#c1c6de;font-size:13px}.footer{display:flex;justify-content:space-between;padding:29px 0;color:#7d849c;font-size:13px}
    @media(max-width:1050px){.hero{grid-template-columns:1fr;gap:32px;padding-top:57px}.hero-copy{max-width:720px}.preview{margin-left:0}.hero h1{max-width:690px}.links{gap:22px}}
    @media(max-width:680px){.wrap{width:min(100% - 32px,1180px)}.nav{height:72px}.brand{font-size:23px}.logo{width:38px;height:38px}.links{display:none}.nav .button{padding:10px 12px;font-size:13px}.hero{padding:43px 0 58px}.hero h1{font-size:42px;letter-spacing:-2.5px}.intro{font-size:16px}.preview{padding:30px 10px 38px}.form-card{padding:23px}.chip{font-size:11px;padding:8px 10px}.chip-top{right:6px;top:0}.chip-bottom{left:6px;bottom:0}.stats{grid-template-columns:repeat(2,1fr);gap:18px}.section,.workspace{padding:60px 0}.features{grid-template-columns:1fr}.dashboard{grid-template-columns:1fr}.sidebar{display:none}.overview{grid-template-columns:1fr}.lead-row{grid-template-columns:1.2fr .8fr .8fr;padding:10px;font-size:11px}.cta{align-items:flex-start;flex-direction:column}.footer{gap:12px;flex-direction:column}.login input{display:block;width:100%;margin:7px 0}.form-card h2{font-size:22px}}
  </style>
</head>
<body>
  <header class="wrap nav"><a href="#top" class="brand"><span class="logo">✦</span>leadly</a><nav class="links"><a href="#platform">Platform</a><a href="#dashboard">Dashboard</a><a href="#demo">Live demo</a></nav><button class="button light" onclick="toggleLogin()">Owner sign in</button></header>
  <main id="top">
    <section class="wrap hero"><div class="hero-copy"><span class="tag"><i class="pulse"></i>Built for high-intent teams</span><h1>Turn every visit into a <span class="gradient">valuable conversation.</span></h1><p class="intro">Leadly gives growing teams beautiful, embeddable lead forms with the secure delivery and reliable processing that your revenue engine deserves.</p><div class="hero-actions"><button class="button" onclick="loadDemo()">Try the live widget →</button><a class="button light" href="#dashboard">Explore dashboard</a></div><p class="note">No credit card · One-line install · Built for any website</p><div class="login" id="login"><b>Explore the demo dashboard</b><br><input id="email" value="owner@alpha.test" aria-label="Email"><input id="password" type="password" value="demo-password" aria-label="Password"><button class="button" onclick="login()">Sign in</button><div id="loginMessage" class="message"></div></div></div><div class="preview"><div class="aurora"></div><div class="form-card"><h2>Stay ahead of the curve.</h2><p>Weekly field notes for teams building what’s next.</p><label class="field-label">WORK EMAIL</label><div class="fake-input">you@company.com</div><label class="field-label">FIRST NAME</label><div class="fake-input">Ava</div><button class="fake-submit">Join the newsletter</button></div><span class="chip chip-top">↗ 43% more leads</span><span class="chip chip-bottom"><b class="chip-dot">●</b>Protected by Leadly</span></div></section>
    <section class="trust"><div class="wrap stats"><div class="stat"><b>One line</b><span>to install any widget</span></div><div class="stat"><b>8 layers</b><span>of public API protection</span></div><div class="stat"><b>2-step</b><span>geolocation fallback</span></div><div class="stat"><b>0 lost leads</b><span>when side effects fail</span></div></div></section>
    <section id="platform" class="wrap section"><span class="eyebrow">THE PLATFORM</span><h2>Everything behind a trustworthy form.</h2><p class="section-copy">A deceptively simple customer experience, backed by the controls a modern engineering team expects.</p><div class="features"><article class="feature"><div class="feature-icon">⌘</div><h3>Embed in minutes</h3><p>Create a form, copy a single script tag, and render it on any customer-facing page.</p></article><article class="feature"><div class="feature-icon">◈</div><h3>Built for the open web</h3><p>Cross-origin delivery, strict validation, bot protection, and rate limits keep forms reliable.</p></article><article class="feature"><div class="feature-icon">↗</div><h3>Lead intelligence</h3><p>Owner dashboards surface submission trends and geographic context without exposing tenant data.</p></article></div><div class="live-demo" id="demo"><h3>Live widget playground</h3><p>This is the actual embeddable widget powered by the public API. Submit a test lead, then sign in to see it in the dashboard.</p><div id="widgetMount"></div></div></section>
    <section id="dashboard" class="workspace"><div class="wrap"><span class="eyebrow">OWNER WORKSPACE</span><h2>Stay close to every new opportunity.</h2><p class="section-copy">A clean operating view for widgets, submissions, and high-level lead activity.</p><div class="panel"><div class="panel-head"><b>Alpha Studio · Overview</b><span id="status" class="live-status">Demo workspace</span></div><div class="dashboard"><aside class="sidebar"><div class="selected">▦ Overview</div><div>◌ Widgets</div><div>✦ Submissions</div><div>◴ Activity</div></aside><div class="main-panel"><div class="overview"><div class="metric"><span>Total leads</span><b id="total">—</b></div><div class="metric"><span>Active widgets</span><b id="widgets">1</b></div><div class="metric"><span>Top region</span><b id="region">—</b></div></div><div class="lead-table"><div class="lead-row heading"><span>Lead</span><span>Widget</span><span>Location</span></div><div id="leadRows"><div class="lead-row"><span>Sign in to view lead activity</span><span>—</span><span>—</span></div></div></div></div></div></div><div class="cta"><div><b>Ready to capture your next conversation?</b><p>Create a form once. Install it everywhere.</p></div><button class="button" onclick="loadDemo()">Launch live demo →</button></div></div></section>
  </main><footer class="wrap footer"><span>© 2026 Leadly</span><span>Secure lead capture for ambitious teams</span></footer>
  <script>
    let token='';
    function toggleLogin(){const x=document.getElementById('login');x.style.display=x.style.display==='block'?'none':'block'}
    function loadDemo(){const box=document.getElementById('demo');box.style.display='block';box.scrollIntoView({behavior:'smooth',block:'center'});const mount=document.getElementById('widgetMount');if(!mount.dataset.loaded){const s=document.createElement('script');s.src='/widget.v1.js?id=widget_welcome';mount.appendChild(s);mount.dataset.loaded='1'}}
    async function login(){const message=document.getElementById('loginMessage');message.textContent='Signing in…';try{const r=await fetch('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:document.getElementById('email').value,password:document.getElementById('password').value})});const d=await r.json();if(!r.ok)throw Error(d.error);token=d.token;message.textContent='Signed in. Your dashboard is live below.';await refreshDashboard()}catch(e){message.textContent='Could not sign in: '+e.message}}
    async function refreshDashboard(){const h={authorization:'Bearer '+token};const [a,s,w]=await Promise.all([fetch('/admin/dashboard/stats',{headers:h}),fetch('/admin/submissions',{headers:h}),fetch('/admin/widgets',{headers:h})]);const stats=await a.json(),subs=await s.json(),widgets=await w.json();document.getElementById('total').textContent=stats.total;document.getElementById('widgets').textContent=widgets.items.length;document.getElementById('region').textContent=Object.keys(stats.byCountry)[0]||'—';document.getElementById('status').textContent='Live owner workspace';document.getElementById('leadRows').innerHTML=subs.items.length?subs.items.slice(0,4).map(x=>'<div class="lead-row"><span>'+safe(x.payload.name||x.payload.email||'New lead')+'</span><span>'+safe(x.widgetId)+'</span><span>'+safe(x.geo?.city||'Unenriched')+'</span></div>').join(''):'<div class="lead-row"><span>No submissions yet</span><span>—</span><span>—</span></div>'}
    function safe(value){const x=document.createElement('div');x.textContent=value;return x.innerHTML}
  </script>
</body></html>`;
